version: '3'

services:

  mongo:
    container_name: mongo
    image: mongo:4.4.2
    ports:
      - 27018:27018
    volumes:
      - mongo-data:/data/db

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.9.3
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  graylog:
    container_name: graylog
    image: graylog/graylog:4.0.1
    environment:
      - GRAYLOG_PASSWORD_SECRET=thestrongestpassword                                                # Must be at least 16 characters
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918 # Default Password: admin
      - GRAYLOG_HTTP_EXTERNAL_URI=http://192.168.99.1:9090/
      - GRAYLOG_WEB_ENDPOINT_URI=http://192.168.99.1:9090/api
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://192.168.99.1:9200
      - GRAYLOG_ELASTICSEARCH_VERSION=7
    depends_on:
      - mongo
      - elasticsearch
    links:
      - mongo
      - elasticsearch
    ports:
      - 9090:9000       # Graylog web interface and REST API
      - 1514:1514       # Syslog TCP
      - 1514:1514/udp   # Syslog UDP
      - 12201:12201     # GELF TCP
      - 12201:12201/udp # GELF UDP
      - 12123:12123/udp # GELF UDP
    volumes:
      - graylog-data:/usr/share/graylog/data/journal

volumes:
  mongo-data:
  elasticsearch-data:
  graylog-data:
