version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - 6432:5432
    volumes:
      - postgres-pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: Keycl0@k123@
      POSTGRES_DB: keycloak

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:latest
    ports:
      - 9000:8080
    volumes:
      - keycloak-data:/opt/jboss/startup-scripts
      - ./keycloak/themes/jconf2020:/opt/jboss/keycloak/themes/jconf2020
      - ./keycloak/files/logging-setup.cli:/opt/jboss/startup-scripts/logging-setup.cli
      - ./keycloak/modules/biz:/opt/jboss/keycloak/modules/biz
    environment:
      DB_VENDOR: postgres
      DB_ADDR: database
      DB_DATABASE: keycloak
      DB_PORT: 6432
      DB_SCHEMA: public
      DB_USER: keycloak
      DB_PASSWORD: Keycl0@k123@
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      PROXY_ADDRESS_FORWARDING: "true"
    depends_on:
      - postgres
    extra_hosts:
      - database:192.168.99.1

volumes:
  postgres-pg-data:
  keycloak-data:
